action_id: trunk-single-player-auto-upgrade
date: 2025-09-03 01:52:29
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1756864349
full_timestamp:
  nanos: 981231000
  seconds: 1756864349
trunk_version: 1.25.0
