action_id: trunk-single-player-auto-upgrade
date: 2025-09-01 16:07:22
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1756742842
full_timestamp:
  nanos: 767297000
  seconds: 1756742842
trunk_version: 1.25.0
