action_id: trunk-single-player-auto-upgrade
date: 2025-08-27 23:26:59
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1756337219
full_timestamp:
  nanos: 973460000
  seconds: 1756337219
trunk_version: 1.25.0
