action_id: trunk-single-player-auto-on-upgrade
date: 2025-08-27 22:31:59
run: trunk on-upgrade --single-player-only -n --no-progress --allow-daemon-start=false --print-summary --scope=check,plugins,runtimes,tools
run_from: ""
trigger: schedule 24h+5m
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1756333919
full_timestamp:
  nanos: 473173000
  seconds: 1756333919
trunk_version: 1.25.0
