action_id: trunk-cache-prune
date: 2025-08-25 20:07:25
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1756152445
full_timestamp:
  nanos: 295344000
  seconds: 1756152445
trunk_version: 1.25.0
