action_id: trunk-cache-prune
date: 2025-09-03 00:52:33
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1756860753
full_timestamp:
  nanos: 326143000
  seconds: 1756860753
trunk_version: 1.25.0
