action_id: trunk-cache-prune
date: 2025-09-02 19:27:29
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1756841249
full_timestamp:
  nanos: 34592000
  seconds: 1756841249
trunk_version: 1.25.0
