action_id: trunk-cache-prune
date: 2025-08-27 22:27:00
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1756333620
full_timestamp:
  nanos: 174307000
  seconds: 1756333620
trunk_version: 1.25.0
