action_id: trunk-cache-prune
date: 2025-09-01 14:55:40
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1756738540
full_timestamp:
  nanos: 426769000
  seconds: 1756738540
trunk_version: 1.25.0
