@echo off
REM Generated by trunk tool 'shfmt'
set PATH=C:\Users\HP\AppData\Local\trunk\tools\shfmt\3.6.0-f249f329eb7123e0a5dd8a13804a150e/bin;C:\Users\HP\AppData\Local\trunk\tools\go\1.21.0-d904f30a230ceffc07122f50d88a122e/bin;C:\Users\HP\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\HP\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=
set GOROOT=C:\Users\HP\AppData\Local\trunk\tools\go\1.21.0-d904f30a230ceffc07122f50d88a122e
set CGO_ENABLED=0
set GO111MODULE=on
set GOPATH=C:\Users\HP\AppData\Local\trunk\tools\shfmt\3.6.0-f249f329eb7123e0a5dd8a13804a150e

start /w /b shfmt %*
