action_id: trunk-whoami
date: 2025-09-02 21:45:19
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Not logged in. Run \"trunk login\" to login\x1b[0m\r\n"
  err: ""
timestamp: 1756849519
full_timestamp:
  nanos: 500928000
  seconds: 1756849519
trunk_version: 1.25.0
