action_id: trunk-whoami
date: 2025-08-27 23:27:02
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Not logged in. Run \"trunk login\" to login\x1b[0m\r\n"
  err: ""
timestamp: 1756337222
full_timestamp:
  nanos: 796553000
  seconds: 1756337222
trunk_version: 1.25.0
