action_id: trunk-whoami
date: 2025-09-01 16:07:25
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Not logged in. Run \"trunk login\" to login\x1b[0m\r\n"
  err: ""
timestamp: 1756742845
full_timestamp:
  nanos: 545986000
  seconds: 1756742845
trunk_version: 1.25.0
