# Rails 7 Production Credentials Template
# ⚠️  TEMPLATE FILE - All values are placeholders
# Copy this content when editing: rails credentials:edit
# 🔑 Generate actual secret key with: rails secret

# Generated secure secret key base (PLACEHOLDER - replace with actual 128-char key)
secret_key_base: "REPLACE_WITH_YOUR_ACTUAL_SECRET_KEY_BASE_128_CHARACTERS_LONG"

# AI Service API Keys
# Replace with your actual API keys

openai:
  api_key: your-openai-api-key-here  # Get from https://platform.openai.com/api-keys
  organization: your-org-id          # Optional

anthropic:
  api_key: your-anthropic-key-here   # Get from https://console.anthropic.com/

huggingface:
  token: your-hf-token-here          # Get from https://huggingface.co/settings/tokens

groq:
  api_key: your-groq-key-here        # Get from https://console.groq.com/keys

cohere:
  api_key: your-cohere-key-here      # Get from https://dashboard.cohere.com/

# Database Configuration
database:
  username: onelastai
  password: onelastai_secure_db_2024_!
  host: localhost
  port: 5432

# Redis Configuration
redis:
  url: redis://localhost:6379
  password: ""                         # Set if using Redis AUTH

# Keycloak SSO
keycloak:
  server_url: http://localhost:8080
  realm: onelastai
  client_id: onelastai-app
  client_secret: your-keycloak-client-secret-placeholder

# Email Configuration (for notifications)
smtp:
  address: smtp.gmail.com
  port: 587
  domain: yourdomain.com
  username: your-email@yourdomain.com
  password: your-email-app-password-here

# File Storage (if using cloud storage)
aws:
  access_key_id: your-aws-access-key-here
  secret_access_key: your-aws-secret-access-key-here
  region: us-east-1
  bucket: onelastai-storage

# Monitoring & Analytics
sentry:
  dsn: your-sentry-dsn

newrelic:
  license_key: your-newrelic-license

# Encryption keys for sensitive data
encryption:
  key: your-additional-encryption-key-for-sensitive-data

# Feature flags
features:
  ai_models_enabled: true
  monitoring_enabled: true
  keycloak_enabled: true
