# OneLastAI Production Credentials - TEMPLATE
# ⚠️  IMPORTANT: Replace ALL placeholder values with your actual credentials
# 📋 See CREDENTIALS_SETUP_GUIDE.md for detailed instructions

# Generated secure secret key base (128 characters)
secret_key_base: 7a2f8c9e1b4d6f3a8c5e2b7d0a3f6c9e1b4d7a0c3f6b9e2d5a8c1f4b7e0d3a6c9f2e5b8d1a4c7f0e3b6d9c2f5a8e1b4d7a0c3f6b9e2d5a8c1f4b7e0d3a6c9f2e5b8d1a4c7f0e3b6d9c2f5a8e1b4d7a0c3f6b9e2d5a8

# 🤖 AI Services - Replace with your actual API keys
openai:
  api_key: "YOUR_OPENAI_API_KEY_HERE"     # Get from: https://platform.openai.com/api-keys
  organization: "your-org-id"             # Optional

anthropic:
  api_key: "YOUR_ANTHROPIC_KEY_HERE"      # Get from: https://console.anthropic.com/

huggingface:
  token: "YOUR_HUGGINGFACE_TOKEN_HERE"    # Get from: https://huggingface.co/settings/tokens

groq:
  api_key: "YOUR_GROQ_API_KEY_HERE"       # Get from: https://console.groq.com/keys

# 🗄️ Database Configuration
database:
  username: "onelastai"
  password: "YOUR_SECURE_DB_PASSWORD_HERE"  # Change from default
  host: "localhost"
  port: 5432

# 🔧 Redis Cache
redis:
  url: "redis://localhost:6379"
  password: ""                            # Set if using Redis AUTH

# 🔐 Keycloak SSO
keycloak:
  server_url: "http://localhost:8080"
  realm: "onelastai"
  client_id: "onelastai-app"
  client_secret: "YOUR_KEYCLOAK_SECRET_HERE"

# 📧 Email Configuration (Optional)
smtp:
  address: "smtp.gmail.com"
  port: 587
  username: "your-email@domain.com"
  password: "YOUR_EMAIL_APP_PASSWORD"

# 🎯 Next Steps:
# 1. Get your OpenAI API key from https://platform.openai.com/api-keys
# 2. Replace "YOUR_OPENAI_API_KEY_HERE" with your actual key
# 3. Update database password for security
# 4. Configure other services as needed
# 5. Use 'rails credentials:edit' for production (recommended)
