# PostgreSQL configuration for OneLastAI platform
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: 127.0.0.1
  database: onelastai_development
  username: onelastai
  password: password

test:
  <<: *default
  host: 127.0.0.1
  database: onelastai_test
  username: onelastai
  password: password

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # Railway will provide DATABASE_URL automatically
  # Fallback configuration if DATABASE_URL is not available
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  database: <%= ENV['DATABASE_NAME'] || 'onelastai_production' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
