# MongoDB configuration for OneLastAI
development:
  clients:
    default:
      uri: mongodb+srv://miczugamark:WSTbNCDS7zfh3e0D@pawns.pwzfji.mongodb.net/onelastai_development?retryWrites=true&w=majority&appName=Pawns
      options:
        server_selection_timeout: 5
        connect_timeout: 10
        socket_timeout: 5
        max_pool_size: 10
        min_pool_size: 1

test:
  clients:
    default:
      uri: mongodb+srv://miczugamark:WSTbNCDS7zfh3e0D@pawns.pwzfji.mongodb.net/onelastai_test?retryWrites=true&w=majority&appName=Pawns
      options:
        server_selection_timeout: 5
        connect_timeout: 10
        socket_timeout: 5
        max_pool_size: 5
        min_pool_size: 1
        read:
          mode: :primary

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb+srv://miczugamark:WSTbNCDS7zfh3e0D@pawns.pwzfji.mongodb.net/onelastai_production?retryWrites=true&w=majority&appName=Pawns' %>
      options:
        max_pool_size: <%= ENV['MONGODB_POOL_SIZE'] || 20 %>
        min_pool_size: 2
        wait_queue_timeout: <%= ENV['MONGODB_TIMEOUT'] || 10 %>
        connect_timeout: 10
        socket_timeout: 5
        ssl: true
        ssl_verify: true
        heartbeat_frequency: 10
        # Read preference for performance
        read:
          mode: :secondary_preferred
          max_staleness_seconds: 120