# MongoDB configuration for OneLastAI - Environment-driven deployment-ready config

development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb+srv://miczugamark:WSTbNCDS7zfh3e0D@pawns.pwzfji.mongodb.net/onelastai_development?retryWrites=true&w=majority&appName=Pawns' %>
      options:
        read:
          mode: :primary
        retry_writes: true
        server_selection_timeout: 10
        connect_timeout: 15
        socket_timeout: 10
        max_pool_size: 10
        min_pool_size: 2
        ssl: true
        ssl_verify: true
        heartbeat_frequency: 10
  options:
    use_utc: false
    log_level: :info

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_TEST_URI'] || 'mongodb+srv://miczugamark:WSTbNCDS7zfh3e0D@pawns.pwzfji.mongodb.net/onelastai_test?retryWrites=true&w=majority&appName=Pawns' %>
      options:
        read:
          mode: :primary
        retry_writes: true
        server_selection_timeout: 5
        connect_timeout: 10
        socket_timeout: 5
        max_pool_size: 5
        min_pool_size: 1
        ssl: true
  options:
    use_utc: false

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        read:
          mode: :primary_preferred
          max_staleness_seconds: 120
        retry_writes: true
        server_selection_timeout: 10
        connect_timeout: 15
        socket_timeout: 10
        max_pool_size: <%= ENV['MONGODB_POOL_SIZE'] || 20 %>
        min_pool_size: 5
        wait_queue_timeout: <%= ENV['MONGODB_TIMEOUT'] || 15 %>
        ssl: true
        ssl_verify: true
        heartbeat_frequency: 10
  options:
    use_utc: true
    log_level: :warn