action_id: trunk-upgrade-available
date: 2025-08-27 06:50:02
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: ca789af89b904bfe96371a18b7c2a1a6)\x1b[0m\r\n"
  err: ""
timestamp: 1756277402
full_timestamp:
  nanos: 257843000
  seconds: 1756277402
trunk_version: 1.25.0
