action_id: trunk-upgrade-available
date: 2025-08-27 09:50:01
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 8a7260fdddde4bbd50adc5351c276117)\x1b[0m\r\n"
  err: ""
timestamp: 1756288201
full_timestamp:
  nanos: 696849000
  seconds: 1756288201
trunk_version: 1.25.0
