action_id: trunk-upgrade-available
date: 2025-08-27 12:50:26
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: a68f6bf1cb4a44cc4d1a89d641372380)\x1b[0m\r\n"
  err: ""
timestamp: 1756299026
full_timestamp:
  nanos: 738343000
  seconds: 1756299026
trunk_version: 1.25.0
