action_id: trunk-upgrade-available
date: 2025-09-02 20:27:36
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: c5bc70dd83d947da4301c7ec7c956aff)\x1b[0m\r\n"
  err: ""
timestamp: 1756844856
full_timestamp:
  nanos: 985639000
  seconds: 1756844856
trunk_version: 1.25.0
