action_id: trunk-upgrade-available
date: 2025-08-27 18:50:07
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 65d8048f6b97459964ea2a863e558ee4)\x1b[0m\r\n"
  err: ""
timestamp: 1756320607
full_timestamp:
  nanos: 362964000
  seconds: 1756320607
trunk_version: 1.25.0
