action_id: trunk-upgrade-available
date: 2025-08-27 16:50:01
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 399e27a3fb754c9f958e8a86f445b8e5)\x1b[0m\r\n"
  err: ""
timestamp: 1756313401
full_timestamp:
  nanos: 667638000
  seconds: 1756313401
trunk_version: 1.25.0
