action_id: trunk-upgrade-available
date: 2025-08-27 19:50:20
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 106274e2931a41909c23c75f12da1479)\x1b[0m\r\n"
  err: ""
timestamp: 1756324220
full_timestamp:
  nanos: 580247000
  seconds: 1756324220
trunk_version: 1.25.0
