action_id: trunk-upgrade-available
date: 2025-08-27 08:50:01
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 92aea11ad1b94c5f7f4a1a1806a7b451)\x1b[0m\r\n"
  err: ""
timestamp: 1756284601
full_timestamp:
  nanos: 725785000
  seconds: 1756284601
trunk_version: 1.25.0
