action_id: trunk-upgrade-available
date: 2025-08-27 13:50:01
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 7281d009d413437af3045de6b113460d)\x1b[0m\r\n"
  err: ""
timestamp: 1756302601
full_timestamp:
  nanos: 874831000
  seconds: 1756302601
trunk_version: 1.25.0
