action_id: trunk-share-with-everyone
date: 2025-08-27 22:27:00
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1756333620
full_timestamp:
  nanos: 213501000
  seconds: 1756333620
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
