action_id: trunk-share-with-everyone
date: 2025-09-02 20:45:18
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1756845918
full_timestamp:
  nanos: 811187000
  seconds: 1756845918
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
